FROM binary-rust-base
RUN cd /home/rust
RUN git clone git@github.com:FindoraNetwork/platform.git

ENV WORK_DIR /home/rust/platform
WORKDIR $WORK_DIR
# RUN cargo build --bin fn --release --target x86_64-unknown-linux-musl
RUN cargo build -p finutils --release
CMD ["sleep", "999999"]