FROM ekidd/rust-musl-builder 
ENV WORK_DIR /src/platform
ENV WASM_DIR /tmp/wasm-js-bindings

# RUN apt update -y && \
#     apt install -y git make curl wget python3-pip protobuf-compiler musl-tools jq libleveldb-dev clang libclang-dev pkg-config libssl-dev gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev
# RUN pip3 install awscli
# RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
# RUN mkdir -p /opt && \
#     cd /opt && \
#     wget https://golang.google.cn/dl/go1.15.7.linux-amd64.tar.gz && \
#     tar -xpf go1.15.7.linux-amd64.tar.gz 
# ENV PATH=$PATH:/opt/go/bin

COPY ./key.tar.gz /key.tar.gz
RUN mkdir -p ~/.ssh && \
    tar -zxf /key.tar.gz -C ~/.ssh && \
    chown -R rust:rust ~/.ssh && \
    sudo rm -rf /key.tar.gz
