FROM binary-rust-base
RUN sudo chmod -R 777 /src

RUN git clone git@github.com:FindoraNetwork/platform.git

ENV WORK_DIR /src/platform
WORKDIR $WORK_DIR
# RUN cargo build --bin fn --release --target x86_64-unknown-linux-musl
RUN cargo build -p finutils --release
CMD ["sleep", "999999"]