name: Develop
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build-and-deploy:
    strategy:
      matrix:
        platform: [aws]
    runs-on: ${{matrix.platform}}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Prepare key
      shell: bash
      run: |
        tar -C ~/.ssh -zcf key.tar.gz ./

    - name: Build rust base image
      shell: bash
      run: |
        make ci_build_rust_base

    - name: Build linux fn
      shell: bash
      run: |
        make ci_build_fn


    - name: Generate env file
      env: 
        REACT_APP_MAILCHIMP_U: ${{ secrets.REACT_APP_MAILCHIMP_U }}
        REACT_APP_MAILCHIMP_ID: ${{ secrets.REACT_APP_MAILCHIMP_ID }}
      shell: bash
      run: |
        touch .env
        echo REACT_APP_MAILCHIMP_U="$REACT_APP_MAILCHIMP_U" >> .env
        echo REACT_APP_MAILCHIMP_ID="$REACT_APP_MAILCHIMP_ID" >> .env

    - name: Build wiki doc
      shell: bash
      run: |
        make ci_build_wiki

    - name: update S3
      shell: bash
      run: |
        aws s3 cp build s3://dev-wiki.findora.org/ --recursive
    
    - name: cloudfront invalidation
      shell: bash
      run: |
        aws cloudfront create-invalidation --distribution-id E3920I9CO27CE0 --paths "/*"

    - name: Cleanup
      shell: bash
      run: |
        make cleanup_image