
name: Deploy
on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    strategy:
      matrix:
        platform: [aws]
    runs-on: ${{matrix.platform}}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Install dependence 
      shell: bash
      run: |
        yarn
    - name: build
      shell: bash
      run: |
        CI=false yarn build
    - name: update S3
      shell: bash
      run: |
        aws s3 cp build s3://wiki.findora.org// --recursive
    - name: cloudfront invalidation
      shell: bash
      run: |
        aws cloudfront create-invalidation --distribution-id E1H48R59LK4RSZ --paths "/"