
name: Deploy
on:
  push:
    branches:
      - main
      - ci
jobs:
  build-and-deploy:
    strategy:
      matrix:
        platform: [aws]
    runs-on: ${{matrix.platform}}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Prepare key
      shell: bash
      run: |
        tar -C ~/.ssh -zcf key.tar.gz ./


    - name: Build
      shell: bash
      run: |
        docker build -t findora-wiki -f .github/workflows/Dockerfile .

    - name: Copy code to local
      shell: bash
      run: |
        docker rm -f findora-wiki || true
        docker run -d --rm --name findora-wiki findora-wiki sleep 99999
        docker cp findora-wiki:/wiki/build ./build
        docker stop -t 0 findora-wiki && docker rm -f findora-wiki
        docker rm $(docker ps -a | awk '{print $1}') || true
        docker rmi -f $(docker images -f "dangling=true" -q) || true
        docker rmi findora-wiki || true


    - name: Build rust base image
      shell: bash
      run: |
        make ci_build_rust_base

    - name: Build linux fn
      shell: bash
      run: |
        make ci_build_fn
    
    - name: Copy fn tp build
      shell: bash
      run: |
        cp fn build/bin/linux/fn

    - name: update S3
      shell: bash
      run: |
        aws s3 cp build s3://wiki.findora.org/ --recursive

    - name: cloudfront invalidation
      shell: bash
      run: |
        aws cloudfront create-invalidation --distribution-id E1H48R59LK4RSZ --paths "/*"